// =============================================================================
// board_top.v
//
// Board-level wrapper for accelerator_top, targeting a Digilent Nexys A7-100T
// (Xilinx Artix-7, xc7a100tcsg324-1) as called out in Section 12.1 of the
// project proposal. Any Artix-7/Spartan-7 board can be targeted by editing
// constraints_nexys_a7.xdc's pin assignments to match; nothing else in this
// file is board-specific beyond the port names.
//
// This wrapper realizes the project's "baseline data path" (Section 9.1):
// the input dataset is preloaded into the input BRAM at configuration time
// via accelerator_top's IN_INIT_FILE parameter (a synthesizable $readmemh
// initial block), so no host interface is required for a bring-up
// demonstration. FIR coefficients are likewise tied off to a fixed value
// generated by python/generate_coeffs.py.
//
// Controls:
//   CPU_RESETN (active-low)  - system reset
//   BTNC                     - momentary press starts one processing pass
//   LED[0]                   - lit while the accelerator is busy
//   LED[1]                   - latches on after the pass completes (done),
//                              cleared by the next start pulse
//
// NUM_MACS_FILT / NUM_MACS_VEC select which compared architecture this
// bitstream implements (Section 5/8 of the proposal):
//   Architecture A (sequential):  NUM_MACS_FILT=1, NUM_MACS_VEC=1 (default)
//   Architecture B (parallel):    NUM_MACS_FILT=8, NUM_MACS_VEC=3
// build.tcl overrides these via `synth_design -generic` so the same source
// file produces both architectures' implementation results.
// =============================================================================

module board_top #(
    parameter NUM_MACS_FILT = 1,
    parameter NUM_MACS_VEC  = 1,
    // Regenerate with python/generate_coeffs.py if the filter design
    // changes; paste the new value from data/coeffs_verilog.vh here.
    parameter [127:0] FIR_COEFFS_Q15 = 128'h011f062314ff23bf23bf14ff0623011f
)(
    input  wire        CLK100MHZ,
    input  wire        CPU_RESETN,
    input  wire        BTNC,
    output wire [15:0] LED
);

    wire rst_n = CPU_RESETN;

    // ---------------------------------------------------------------
    // Synchronize the button and detect a single rising edge, so a
    // momentary press generates exactly one start pulse regardless of
    // how many clock cycles the button is physically held.
    // ---------------------------------------------------------------
    reg [2:0] btn_sync;
    always @(posedge CLK100MHZ or negedge rst_n) begin
        if (!rst_n)
            btn_sync <= 3'b000;
        else
            btn_sync <= {btn_sync[1:0], BTNC};
    end
    wire start_pulse = btn_sync[1] & ~btn_sync[2];

    // ---------------------------------------------------------------
    // Accelerator instance
    // ---------------------------------------------------------------
    wire busy, done;

    accelerator_top #(
        .NUM_MACS_FILT(NUM_MACS_FILT),
        .NUM_MACS_VEC(NUM_MACS_VEC),
        .NUM_SAMPLES(64),
        .ADDR_W(6),
        .IN_INIT_FILE("data/input.mem")
    ) u_accel (
        .clk(CLK100MHZ),
        .rst_n(rst_n),
        .start(start_pulse),
        .busy(busy),
        .done(done),
        .coeffs_in(FIR_COEFFS_Q15),
        .in_wr_en(1'b0),
        .in_wr_addr(6'b0),
        .in_wr_data(48'b0),
        .out_rd_addr(6'b0),
        .out_rd_data()          // unused on this minimal demo wrapper;
                                 // read results back via ILA/JTAG-to-AXI,
                                 // or extend with a UART readback path
                                 // (Section 9.2 optional extension)
    );

    // ---------------------------------------------------------------
    // Status LEDs
    // ---------------------------------------------------------------
    reg done_latch;
    always @(posedge CLK100MHZ or negedge rst_n) begin
        if (!rst_n)
            done_latch <= 1'b0;
        else if (start_pulse)
            done_latch <= 1'b0;
        else if (done)
            done_latch <= 1'b1;
    end

    assign LED[0]    = busy;
    assign LED[1]    = done_latch;
    assign LED[15:2] = 14'b0;

endmodule
