#!/usr/bin/env python3
"""
generate_coeffs.py

Designs the 8-tap FIR low-pass filter used by the accelerator (Section 5.1
of the project proposal) and converts the coefficients to Q1.15 fixed-point,
matching the hardware's fixed-point convention in fir_filter.v.

Design target: a wearable accelerometer sampled at FS_HZ, with motion-
relevant energy below CUTOFF_HZ and higher-frequency content treated as
sensor noise to be attenuated. TAPS=8 matches the RTL's TAPS parameter.

Outputs (written to ../data/):
  coeffs_q15.txt      - human-readable table: index, float, Q1.15 int, hex
  coeffs_pack.hex      - single line, 32 hex digits: the packed 128-bit
                         {h7,h6,...,h1,h0} bus, ready for $readmemh into a
                         reg [TAPS*COEF_W-1:0] (matches coeffs_in ordering
                         used throughout the RTL: index 0 = tap 0).
  coeffs_verilog.vh   - a ready-to-paste Verilog localparam literal, for
                         hardcoding coefficients into a board top module
                         where no host coefficient-loading interface exists.

Usage:
    python3 generate_coeffs.py
"""

import numpy as np
from scipy.signal import firwin

TAPS       = 8
COEF_W     = 16
FRAC_BITS  = 15          # Q1.15
FS_HZ      = 100.0       # assumed IMU sample rate
CUTOFF_HZ  = 10.0        # low-pass cutoff

OUT_DIR = "../data"


def to_q15(x: np.ndarray) -> np.ndarray:
    """Convert float array in [-1, 1) to signed 16-bit Q1.15 integers,
    matching the saturation convention used in the RTL (clip, don't wrap)."""
    scaled = np.round(x * (1 << FRAC_BITS)).astype(np.int64)
    qmax = (1 << (COEF_W - 1)) - 1   # 32767
    qmin = -(1 << (COEF_W - 1))      # -32768
    return np.clip(scaled, qmin, qmax).astype(np.int32)


def main():
    # Windowed-sinc low-pass FIR design (Hamming window), normalized so the
    # DC gain (sum of taps) is close to 1.0 in floating point before
    # quantization -- appropriate for a noise-suppressing low-pass filter.
    h_float = firwin(TAPS, cutoff=CUTOFF_HZ, fs=FS_HZ, window="hamming")
    h_float = h_float / np.sum(h_float)  # normalize DC gain to exactly 1.0

    h_q15 = to_q15(h_float)

    print(f"8-tap FIR low-pass, fs={FS_HZ} Hz, cutoff={CUTOFF_HZ} Hz")
    print(f"{'tap':>4} {'float':>10} {'Q1.15':>8} {'hex':>6}")
    for i, (f, q) in enumerate(zip(h_float, h_q15)):
        print(f"{i:>4} {f:>10.6f} {q:>8d} {q & 0xFFFF:>04x}")

    dc_gain_q15 = np.sum(h_q15) / (1 << FRAC_BITS)
    print(f"\nSum of float taps : {np.sum(h_float):.6f}")
    print(f"Sum of Q1.15 taps  : {np.sum(h_q15)} (~{dc_gain_q15:.6f} in real units)")

    # ---------------- coeffs_q15.txt ----------------
    with open(f"{OUT_DIR}/coeffs_q15.txt", "w") as f:
        f.write(f"# 8-tap FIR low-pass, fs={FS_HZ} Hz, cutoff={CUTOFF_HZ} Hz, Q1.15\n")
        f.write(f"# tap  float        q15      hex\n")
        for i, (fl, q) in enumerate(zip(h_float, h_q15)):
            f.write(f"{i}  {fl:.8f}  {q}  {q & 0xFFFF:04x}\n")

    # ---------------- coeffs_pack.hex ----------------
    # Packed bus layout matches mac_engine/fir_filter convention:
    #   coeffs_in[i*COEF_W +: COEF_W] = h[i]
    # For $readmemh into a single reg [TAPS*COEF_W-1:0], the most
    # significant hex digits correspond to the highest tap index.
    packed = 0
    for i, q in enumerate(h_q15):
        packed |= (int(q) & 0xFFFF) << (i * COEF_W)
    hex_digits = TAPS * COEF_W // 4  # 32 hex digits for 128 bits
    with open(f"{OUT_DIR}/coeffs_pack.hex", "w") as f:
        f.write(f"{packed:0{hex_digits}x}\n")

    # ---------------- coeffs_verilog.vh ----------------
    with open(f"{OUT_DIR}/coeffs_verilog.vh", "w") as f:
        f.write("// Auto-generated by generate_coeffs.py -- do not edit by hand.\n")
        f.write(f"// 8-tap FIR low-pass, fs={FS_HZ} Hz, cutoff={CUTOFF_HZ} Hz, Q1.15\n")
        f.write(f"localparam [{TAPS*COEF_W-1}:0] FIR_COEFFS_Q15 = {TAPS*COEF_W}'h{packed:0{hex_digits}x};\n")

    print(f"\nWrote {OUT_DIR}/coeffs_q15.txt")
    print(f"Wrote {OUT_DIR}/coeffs_pack.hex")
    print(f"Wrote {OUT_DIR}/coeffs_verilog.vh")


if __name__ == "__main__":
    main()
